# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-17 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('cid', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('post_pay', models.BooleanField(default=False)),
            ],
        ),
    ]
