# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-06 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
from invoices.models import Invoice


def set_values_created_at(app, schema):
    """ Set old records as `date_issue` as `created_at`"""
    invoices = Invoices.objects.all()
    for invoice in invoices:
        invoice.date_issue = invoice.created_at
        invoice.save(update_fields=['date_issue'])


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_invoice-model'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_issue',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(set_values_created_at)
    ]
